export enum MeetingStatusEnum {
  CANCELLED = 'CANCELLED',
  PENDING = 'PENDING',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  STARTED = 'STARTED',
  ENDED = 'ENDED',
  UPCOMING = 'UPCOMING',
  REJECTED = 'REJECTED',
}
